FROM php:7.0.14-apache
ENV PHP_INI_DIR /usr/local/etc/php
RUN apt-get update \
  && docker-php-source extract \
  && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng12-dev libmcrypt-dev libldap2-dev vim less git \
  && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu \
  && docker-php-ext-install pdo pdo_mysql mysqli mbstring gd iconv mcrypt \
  && curl -sS https://getcomposer.org/installer | php \
  && mv /var/www/html/composer.phar /usr/bin/composer \
  && chmod +x /usr/bin/composer \
  && a2enmod rewrite
RUN apt-get install locales
RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8
ENV LC_CTYPE ja_JP.UTF-8
RUN localedef -f UTF-8 -i ja_JP ja_JP.utf8

